x='lokeshit'
print(x)
print(x.capitalize())
print(x.title())
print(x.upper())
print(x.lower())
print(x.isupper())
print(x.islower())
print(x.isdigit())
y="1234"
print(y)
print(y.isdigit())
print(y.isalpha())
