x=input("enter int value")
print(type(x))
i=int(x)
print(type(i))
y=input("enter float value")
print(type(y))
j=float(y)
print(type(j))
z=input("enter complex number")
print(type(z))
k=complex(z)
print(type(k))
p=input("enter bool value")
print(type(p))
l=bool(p)
print(type(l))
